"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Status = { key: string; label: string; ok: boolean; detail: string; lastSync?: string | null; failedCount?: number };
type Overview = { generatedAt: string; statuses: Status[]; counts: Array<{ table: string; label: string; count: number; ok: boolean; error?: string }>; anomalies: Array<{ category: string; ref: string; happenedAt: string | null; detail: string }>; monitorLogs: Array<Record<string, unknown>> };
const severity = (item: Status) => item.ok ? ["正常", "border-emerald-500 bg-emerald-50 text-emerald-700"] : Number(item.failedCount || 0) >= 3 ? ["嚴重", "border-red-600 bg-red-50 text-red-700"] : Number(item.failedCount || 0) ? ["警告", "border-orange-500 bg-orange-50 text-orange-700"] : ["注意", "border-carcare-yellow bg-carcare-yellow/10 text-neutral-900"];

export default function MaintenanceHealthV2() {
  const [overview, setOverview] = useState<Overview | null>(null);
  const [message, setMessage] = useState("載入中…");
  async function load() { try { const response = await fetch(`/api/maintenance/overview?t=${Date.now()}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) { if (response.status === 401) location.href = "/maintenance/login"; throw new Error(result.message || "讀取失敗"); } setOverview(result.overview); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "讀取失敗"); } }
  useEffect(() => { void load(); }, []);
  const score = useMemo(() => { if (!overview) return 0; const failures = overview.statuses.filter((item) => !item.ok).length; return Math.max(0, 100 - failures * 10 - overview.anomalies.length * 2); }, [overview]);
  return <main className="min-h-screen bg-carcare-bg p-4 md:p-8"><div className="mx-auto max-w-7xl space-y-5">
    <header className="card flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-sm font-black text-carcare-yellow">PEIWAY Monitor V2</p><h1 className="text-2xl font-black">絕對後台健康監控</h1><p className="text-sm text-neutral-500">唯讀檢視 Supabase、N8N、Google Sheets、PDF、Storage 與同步佇列。</p></div><div className="flex gap-2"><Link href="/maintenance/dashboard" className="secondary-btn">返回 Monitor</Link><button className="primary-btn" onClick={() => void load()}>重新偵測</button></div></header>
    {message ? <div className="card font-bold">{message}</div> : null}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="card"><p className="text-sm font-bold text-neutral-500">系統健康分數</p><p className={`mt-2 text-4xl font-black ${score < 80 ? "text-red-600" : "text-carcare-yellow"}`}>{score}</p></div><div className="card"><p className="text-sm font-bold text-neutral-500">監控通道</p><p className="mt-2 text-4xl font-black text-carcare-yellow">{overview?.statuses.length || 0}</p></div><div className="card"><p className="text-sm font-bold text-neutral-500">異常事件</p><p className="mt-2 text-4xl font-black text-red-600">{overview?.anomalies.length || 0}</p></div><div className="card"><p className="text-sm font-bold text-neutral-500">最後檢查</p><p className="mt-3 font-black">{overview?.generatedAt ? new Date(overview.generatedAt).toLocaleString("zh-TW") : "-"}</p></div></div>
    <section className="card"><h2 className="text-lg font-black">通道健康狀態</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{overview?.statuses.map((item) => { const [label, style] = severity(item); return <div key={item.key} className={`rounded-xl border-l-4 p-4 ${style}`}><div className="flex justify-between gap-2"><strong>{item.label}</strong><span className="rounded-full bg-white/70 px-2 py-1 text-xs font-black">{label}</span></div><p className="mt-2 text-sm">{item.detail}</p><p className="mt-2 text-xs">最後同步：{item.lastSync ? new Date(item.lastSync).toLocaleString("zh-TW") : "尚無紀錄"} · 失敗 {item.failedCount || 0}</p></div>; })}</div></section>
    <section className="grid gap-5 xl:grid-cols-2"><div className="card"><h2 className="text-lg font-black">資料表可用性</h2><div className="mt-4 space-y-2">{overview?.counts.map((item) => <div key={item.table} className="flex justify-between rounded-xl bg-neutral-50 p-3"><span>{item.ok ? "🟢" : "🔴"} {item.label}</span><strong>{item.ok ? `${item.count} 筆` : item.error || "讀取失敗"}</strong></div>)}</div></div><div className="card"><h2 className="text-lg font-black">自動異常偵測</h2><div className="mt-4 space-y-3">{overview?.anomalies.map((item, index) => <div key={`${item.ref}-${index}`} className="rounded-xl border border-red-200 bg-red-50 p-3"><strong>{item.category}</strong><p className="text-sm">{item.ref} · {item.detail}</p><p className="text-xs text-neutral-500">{item.happenedAt ? new Date(item.happenedAt).toLocaleString("zh-TW") : "-"}</p></div>)}{overview && !overview.anomalies.length ? <div className="rounded-xl bg-emerald-50 p-4 font-bold text-emerald-700">目前未偵測到異常。</div> : null}</div></div></section>
  </div></main>;
}
