(function(){
var KEY='car-beauty-full-v8';var ADMIN='admin1234',FINANCE='boss1688';
var seed={view:'home',authed:false,finance:false,role:'staff',cfg:{stores:['三重','桃園','新竹','台南','台北','台中','高雄'],status:['待確認','已排車','施工中','已完工','取消'],pay:['現金','匯款','刷卡','定金'],source:['FB','IG','Google','朋友介紹','TK'],workers:[{id:'W001',name:'阿凱',store:'三重'},{id:'W002',name:'Mina',store:'桃園'},{id:'W003',name:'施工A組',store:'新竹'}],packages:[{id:'P001',name:'9999內外超值',text:'內外清潔與基礎美容',price:9999,stores:['三重','桃園','新竹','台南'],img:''},{id:'P002',name:'內裝深層拆洗',text:'座椅地毯門板深層處理',price:7800,stores:['三重','台北','台中'],img:''},{id:'P003',name:'玻璃油膜鍍膜',text:'雨天視線與玻璃撥水',price:3200,stores:['桃園','新竹','高雄'],img:''}],addons:[{id:'A001',name:'寵物異味',text:'寵物味與毛髮加強',price:1500,stores:['三重','桃園','新竹'],img:''},{id:'A002',name:'煙味處理',text:'煙味霉味異味處理',price:1800,stores:['三重','台北','台中','高雄'],img:''}]},orders:[{id:'O20260706001',name:'王先生',phone:'0911222333',plate:'ABC-1234',car:'Tesla Model Y',year:'2023',date:'2026-07-07',time:'10:00',store:'三重',packageId:'P001',addonIds:['A001'],source:'FB',budget:'12000',care:'白內裝乾淨度',job:'工程師',note:'白內裝加強',status:'已排車',workerId:'W001',pay:'匯款'}],customers:[],logs:['系統建立'],outbox:[]};
var db=load();syncCustomers();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||clone(seed)}catch(e){return clone(seed)}}function clone(x){return JSON.parse(JSON.stringify(x))}function save(){localStorage.setItem(KEY,JSON.stringify(db))}function q(id){return document.getElementById(id)}function v(id){return(q(id)&&q(id).value||'').trim()}function money(n){return '$'+Number(n||0).toLocaleString('zh-TW')}function log(t){db.logs.unshift(new Date().toLocaleString('zh-TW')+' '+t);save()}function go(x){db.view=x;save();render()}function pkg(id){return db.cfg.packages.find(x=>x.id===id)||{name:'-',price:0}}function addon(id){return db.cfg.addons.find(x=>x.id===id)||{name:'',price:0}}function worker(id){return db.cfg.workers.find(x=>x.id===id)||{name:'-'}}function orderTotal(o){return pkg(o.packageId).price+(o.addonIds||[]).reduce((s,id)=>s+addon(id).price,0)}function addonNames(ids){return(ids||[]).map(id=>addon(id).name).filter(Boolean).join('、')||'-'}
function shell(title,body,admin){q('app').innerHTML='<header class="topbar worktop"><div><h1>'+title+'</h1><small>'+(admin?'管理後台':'前台工作台')+' · '+(navigator.onLine?'線上':'離線可用')+'</small></div><button class="ghost" onclick="go(''+(admin?'home':'adminLogin')+'')">'+(admin?'回前台':'後台')+'</button></header>'+(admin&&db.authed?adminMenu():'')+'<main class="page">'+body+'</main><nav class="bottom-nav">'+tab('home','工作台')+tab('frontForm','預約')+tab('orders','訂單')+tab('calendar','行事曆')+tab('customers','客戶')+'</nav>'}
function tab(id,t){return'<button class="'+(db.view===id?'active':'')+'" onclick="go(''+id+'')"><strong>'+t[0]+'</strong>'+t+'</button>'}function adminMenu(){return'<div class="admin-menu">'+['adminHome:總覽','config:基礎配置','workers:施工人員','priceAdmin:價目管理','orders:訂單管理','calendar:行事曆','customers:客戶管理','reports:財務報表','logs:紀錄'].map(x=>{var a=x.split(':');return'<button onclick="go(''+a[0]+'')">'+a[1]+'</button>'}).join('')+'<button class="secondary" onclick="logout()">登出</button></div>'}
function stat(a,b){return'<article class="card stat-card"><span>'+a+'</span><strong>'+b+'</strong></article>'}function tool(id,t){return'<button class="tool" onclick="go(''+id+'')"><strong>'+t[0]+'</strong><span>'+t+'</span></button>'}
function home(){var pending=db.orders.filter(o=>o.status==='待確認').length;shell('汽車美容預約工作台','<section class="banner">全流程預約、配置、訂單、排程、客戶與報表集中管理</section><section class="stats-grid">'+stat('待確認',pending)+stat('今日排程',todayOrders().length)+stat('本月營收',money(monthRevenue()))+stat('客戶數',db.customers.length)+'</section><section class="tool-grid">'+tool('frontForm','前台預約')+tool('pasteForm','貼上填單')+tool('evalForm','後台評估')+tool('siteForm','現場預約')+tool('orders','訂單管理')+tool('calendar','行事曆')+tool('customers','客戶資料')+tool('price','價目菜單')+tool('adminLogin','管理後台')+'</section><h2>待辦工單</h2><section class="todo-list">'+todos()+'</section>')}
function todos(){var list=db.orders.filter(o=>o.status!=='已完工'&&o.status!=='取消').slice(0,6);return list.length?list.map(o=>'<article class="todo"><span class="badge">!</span><div><b>'+o.status+'</b><p>'+o.name+' '+o.date+' '+o.time+' '+o.store+' '+o.plate+'</p></div><button onclick="openOrder(''+o.id+'')">處理</button></article>').join(''):'<div class="empty">目前沒有待辦</div>'}
function field(l,id,need,val){return'<div class="field"><label>'+l+'</label><input id="'+id+'" '+(need?'required':'')+' value="'+(val||'')+'"></div>'}function area(l,id){return'<div class="field"><label>'+l+'</label><textarea id="'+id+'"></textarea></div>'}function sel(l,id,arr,val){return'<div class="field"><label>'+l+'</label><select id="'+id+'">'+arr.map(x=>{var value=typeof x==='string'?x:x.value,label=typeof x==='string'?x:x.label;return'<option value="'+value+'" '+(value==val?'selected':'')+'>'+label+'</option>'}).join('')+'</select></div>'}function multi(l,name,arr,vals){vals=vals||[];return'<div class="field"><label>'+l+'</label>'+arr.map(x=>'<label class="choice"><input name="'+name+'" type="checkbox" value="'+x.value+'" '+(vals.includes(x.value)?'checked':'')+' onchange="calcMoney()"> '+x.label+'</label>').join('')+'</div>'}function checked(n){return Array.from(document.querySelectorAll('input[name="'+n+'"]:checked')).map(i=>i.value)}
function pkgOptions(store){return db.cfg.packages.filter(p=>!store||p.stores.includes(store)).map(p=>({value:p.id,label:p.name+' '+money(p.price)}))}function addonOptions(store){return db.cfg.addons.filter(a=>!store||a.stores.includes(store)).map(a=>({value:a.id,label:a.name+' '+money(a.price)}))}
function formBase(type,extra){shell(type,'<form class="grid two" onsubmit="saveOrder(event,''+type+'')"><section class="card"><h2>客戶與車輛</h2>'+field('稱呼','name',true)+field('聯絡電話','phone',true)+field('車牌','plate',true)+field('車型','car',true)+field('年份','year',true)+sel('預約門市','store',db.cfg.stores)+field('預約日期','date',true,new Date().toISOString().slice(0,10))+sel('預約時間','time',['09:00','10:00','11:00','13:00','14:00','15:00','16:00'])+'</section><section class="card"><h2>方案與來源</h2>'+sel('預約方案','packageId',pkgOptions())+multi('加購項目','addons',addonOptions())+sel('如何得知我們','source',db.cfg.source)+sel('付款方式','pay',db.cfg.pay)+field('預算','budget',false)+(extra||'')+area('其它備註','note')+'<h3>總金額 <span class="price" id="sum">$0</span></h3><button class="gold">提交建立訂單</button></section></form>') ; setTimeout(calcMoney,0)}
function frontForm(){formBase('前台預約表單')}function siteForm(){formBase('現場預約管理')}function evalForm(){formBase('後台預約評估表',field('最在意愛車的地方是？','care',false)+field('職業','job',false))}
function pasteForm(){shell('複製貼上快速填單','<section class="card"><p>貼上客戶傳來的預約資料，系統會自動帶入欄位。</p><textarea id="pasteText" style="min-height:260px">🔴【預約資料填寫】

1️⃣ 稱呼：
2️⃣ 聯絡電話：
3️⃣ 車牌：
4️⃣ 車型：
5️⃣ 年份：
6️⃣ 預約方案：
7️⃣ 預約門市：
8️⃣ 預約日期 / 時間：
9️⃣ 如何得知我們（FB / IG / Google / 朋友介紹）：
➡️其它備註：</textarea><button class="gold" onclick="parsePaste()">自動填入表單</button></section><div id="pasteResult"></div>')}
function parsePaste(){var t=v('pasteText'),m=k=>((t.match(new RegExp(k+'[：: ]*([^\n]+)'))||[])[1]||'').trim();var dt=m('預約日期 / 時間')||m('預約日期');var parts=dt.split(/s+/);q('pasteResult').innerHTML='<form class="grid two" onsubmit="saveOrder(event,'貼上預約')"><section class="card">'+field('稱呼','name',true,m('稱呼'))+field('聯絡電話','phone',true,m('聯絡電話'))+field('車牌','plate',true,m('車牌'))+field('車型','car',true,m('車型'))+field('年份','year',true,m('年份'))+sel('預約門市','store',db.cfg.stores,m('預約門市'))+field('預約日期','date',true,parts[0]||'')+field('預約時間','time',true,parts[1]||'')+'</section><section class="card">'+sel('預約方案','packageId',pkgOptions(),findPkg(m('預約方案')))+multi('加購項目','addons',addonOptions())+sel('如何得知我們','source',db.cfg.source,m('如何得知我們'))+sel('付款方式','pay',db.cfg.pay)+area('其它備註','note')+'<h3>總金額 <span class="price" id="sum">$0</span></h3><button class="gold">提交建立訂單</button></section></form>';q('note').value=m('其它備註')||'';calcMoney()}
function findPkg(name){var p=db.cfg.packages.find(x=>name&&x.name.includes(name));return p?p.id:db.cfg.packages[0].id}function calcMoney(){var p=pkg(v('packageId'));var sum=p.price+checked('addons').reduce((s,id)=>s+addon(id).price,0);var s=q('sum');if(s)s.textContent=money(sum)}
function saveOrder(e,type){e.preventDefault();var o={id:'O'+Date.now(),name:v('name'),phone:v('phone'),plate:v('plate'),car:v('car'),year:v('year'),date:v('date'),time:v('time'),store:v('store'),packageId:v('packageId'),addonIds:checked('addons'),source:v('source'),pay:v('pay'),budget:v('budget'),care:v('care'),job:v('job'),note:v('note'),status:'待確認',workerId:''};db.orders.unshift(o);db.outbox.push({type:'order',id:o.id});syncCustomers();log('建立訂單 '+o.id);save();alert('訂單已建立，已同步到訂單/行事曆/客戶資料');go('orders')}
function orders(){var st=v('filterStatus'),store=v('filterStore');var list=db.orders.filter(o=>(!st||o.status===st)&&(!store||o.store===store));shell('訂單管理','<section class="card row">'+sel('狀態篩選','filterStatus',[''].concat(db.cfg.status),st)+sel('門市篩選','filterStore',[''].concat(db.cfg.stores),store)+'<button onclick="orders()">篩選</button><button onclick="exportOrders()">匯出Excel CSV</button></section><section class="table-wrap"><table><thead><tr><th>訂單</th><th>客戶/車輛</th><th>排程</th><th>方案/金額</th><th>狀態/施工</th></tr></thead><tbody>'+list.map(o=>'<tr><td>'+o.id+'</td><td>'+o.name+'<br>'+o.phone+'<br>'+o.car+' '+o.plate+'</td><td>'+o.date+' '+o.time+'<br>'+o.store+'</td><td>'+pkg(o.packageId).name+'<br>'+addonNames(o.addonIds)+'<br>'+money(orderTotal(o))+'</td><td>'+selMini('st-'+o.id,db.cfg.status,o.status,'changeStatus(''+o.id+'')')+selMini('wk-'+o.id,[{value:'',label:'未指定'}].concat(db.cfg.workers.filter(w=>!o.store||w.store===o.store).map(w=>({value:w.id,label:w.name}))),o.workerId,'changeWorker(''+o.id+'')')+'<button onclick="openOrder(''+o.id+'')">詳情</button></td></tr>').join('')+'</tbody></table></section>',db.authed)}
function selMini(id,arr,val,on){return'<select id="'+id+'" onchange="'+on+'">'+arr.map(x=>{var value=typeof x==='string'?x:x.value,label=typeof x==='string'?x:x.label;return'<option value="'+value+'" '+(value==val?'selected':'')+'>'+label+'</option>'}).join('')+'</select>'}function changeStatus(id){var o=db.orders.find(x=>x.id===id);o.status=v('st-'+id);if(o.status==='已完工')syncCustomers();log(id+' 狀態改為 '+o.status);save();orders()}function changeWorker(id){var o=db.orders.find(x=>x.id===id);o.workerId=v('wk-'+id);log(id+' 指派施工 '+worker(o.workerId).name);save();orders()}function openOrder(id){var o=db.orders.find(x=>x.id===id);shell('訂單詳情','<section class="card"><h2>'+o.name+' '+o.plate+'</h2><p>'+o.phone+'<br>'+o.car+' '+o.year+'<br>'+o.date+' '+o.time+' '+o.store+'</p><p>'+pkg(o.packageId).name+' / '+addonNames(o.addonIds)+'</p><p class="price">'+money(orderTotal(o))+'</p><p>狀態：'+o.status+'　施工：'+worker(o.workerId).name+'</p><p>備註：'+(o.note||'-')+'</p></section>',db.authed)}
function calendar(){var store=v('calStore'),st=v('calStatus'),day=v('calDate');var list=db.orders.filter(o=>(!store||o.store===store)&&(!st||o.status===st)&&(!day||o.date===day));shell('行事曆排程管理','<section class="card row">'+sel('門市','calStore',[''].concat(db.cfg.stores),store)+field('日期','calDate',false,day)+sel('狀態','calStatus',[''].concat(db.cfg.status),st)+'<button onclick="calendar()">篩選</button></section><section class="grid cards">'+list.map(o=>'<article class="card"><h3>'+o.date+' '+o.time+'</h3><p>'+o.store+' / '+o.name+' / '+o.plate+'</p><p>'+pkg(o.packageId).name+'</p><span class="tag orange">'+o.status+'</span><p>施工：'+worker(o.workerId).name+'</p></article>').join('')+'</section>',db.authed)}
function customers(){syncCustomers();var s=v('custSearch'),store=v('custStore');var list=db.customers.filter(c=>(!store||c.store===store)&&(!s||[c.name,c.phone,c.plate].join(' ').includes(s)));shell('客戶資料管理','<section class="card row">'+field('搜尋姓名/電話/車牌','custSearch',false,s)+sel('門市','custStore',[''].concat(db.cfg.stores),store)+'<button onclick="customers()">搜尋</button><button onclick="exportCustomers()">匯出客戶</button></section><section class="table-wrap"><table><thead><tr><th>客戶編號</th><th>稱呼</th><th>電話</th><th>車牌/車型</th><th>門市</th><th>首次預約</th><th>消費總額</th></tr></thead><tbody>'+list.map(c=>'<tr><td>'+c.id+'</td><td>'+c.name+'</td><td>'+c.phone+'</td><td>'+c.plate+'<br>'+c.car+'</td><td>'+c.store+'</td><td>'+c.firstDate+'</td><td>'+money(c.total)+'</td></tr>').join('')+'</tbody></table></section>',db.authed)}
function syncCustomers(){var map={};db.orders.forEach(o=>{var k=o.phone||o.plate;if(!map[k])map[k]={id:'C'+Object.keys(map).length,name:o.name,phone:o.phone,plate:o.plate,car:o.car,store:o.store,firstDate:o.date,total:0,note:o.note};if(o.status==='已完工')map[k].total+=orderTotal(o);if(o.date<map[k].firstDate)map[k].firstDate=o.date});db.customers=Object.values(map);save()}
function price(){shell('價目菜單','<section class="grid cards">'+db.cfg.packages.map(p=>'<article class="card"><h3>'+p.name+'</h3><p>'+p.text+'</p><p>'+p.stores.join('、')+'</p><p class="price">'+money(p.price)+'</p></article>').join('')+'</section>')}
function adminLogin(){shell('管理後台登入','<section class="card login-card"><p>請輸入管理密碼</p><input id="pwd" type="password"><button class="gold" onclick="login()">登入後台</button></section>',true)}function login(){if(v('pwd')===ADMIN){db.authed=true;db.role='admin';save();go('adminHome')}else alert('密碼錯誤')}function logout(){db.authed=false;db.finance=false;db.role='staff';save();go('home')}function adminHome(){if(!db.authed)return adminLogin();shell('管理後台總覽','<section class="stats-grid">'+stat('訂單數',db.orders.length)+stat('門市數',db.cfg.stores.length)+stat('施工人員',db.cfg.workers.length)+stat('營收',money(monthRevenue()))+'</section><section class="tool-grid">'+tool('config','基礎配置')+tool('workers','施工人員')+tool('priceAdmin','價目管理')+tool('orders','訂單管理')+tool('calendar','行事曆')+tool('customers','客戶管理')+tool('reports','財務報表')+'</section>',true)}
function config(){if(!db.authed)return adminLogin();shell('基礎配置管理','<section class="grid two">'+cfgBox('門市選項','stores')+cfgBox('訂單狀態','status')+cfgBox('付款方式','pay')+cfgBox('得知管道','source')+'</section>',true)}function cfgBox(title,key){return'<article class="card"><h3>'+title+'</h3><p>'+db.cfg[key].join('、')+'</p><input id="cfg-'+key+'" placeholder="新增選項"><button onclick="addCfg(''+key+'')">新增</button></article>'}function addCfg(key){var x=v('cfg-'+key);if(x&&!db.cfg[key].includes(x)){db.cfg[key].push(x);log('新增配置 '+x);save();config()}}
function workers(){if(!db.authed)return adminLogin();shell('施工人員管理','<section class="card row"><input id="wId" placeholder="人員編號"><input id="wName" placeholder="姓名">'+sel('負責門市','wStore',db.cfg.stores)+'<button onclick="addWorker()">新增施工人員</button></section><section class="table-wrap"><table><thead><tr><th>編號</th><th>姓名</th><th>門市</th><th></th></tr></thead><tbody>'+db.cfg.workers.map(w=>'<tr><td>'+w.id+'</td><td>'+w.name+'</td><td>'+w.store+'</td><td><button onclick="delWorker(''+w.id+'')">刪除</button></td></tr>').join('')+'</tbody></table></section>',true)}function addWorker(){db.cfg.workers.push({id:v('wId')||('W'+Date.now()),name:v('wName'),store:v('wStore')});log('新增施工人員');save();workers()}function delWorker(id){db.cfg.workers=db.cfg.workers.filter(w=>w.id!==id);save();workers()}
function priceAdmin(){if(!db.authed)return adminLogin();shell('價目菜單管理','<section class="card row"><input id="pName" placeholder="方案名稱"><input id="pText" placeholder="方案說明"><input id="pPrice" placeholder="金額"><input id="pStores" placeholder="適用門市，以、分隔"><input id="pImg" type="file" accept="image/*"><button onclick="addPackage()">新增方案</button></section><section class="grid cards">'+db.cfg.packages.map(p=>'<article class="card"><h3>'+p.id+' '+p.name+'</h3><p>'+p.text+'</p><p>'+p.stores.join('、')+'</p><p class="price">'+money(p.price)+'</p><button onclick="delPackage(''+p.id+'')">刪除</button></article>').join('')+'</section>',true)}function addPackage(){db.cfg.packages.push({id:'P'+Date.now(),name:v('pName'),text:v('pText'),price:Number(v('pPrice')||0),stores:(v('pStores')||db.cfg.stores.join('、')).split(/[、,]/),img:q('pImg').files[0]?.name||''});log('新增方案');save();priceAdmin()}function delPackage(id){db.cfg.packages=db.cfg.packages.filter(p=>p.id!==id);save();priceAdmin()}
function reports(){if(!db.authed)return adminLogin();if(!db.finance)return shell('財務二次驗證','<section class="card login-card"><p>請輸入財務密碼</p><input id="fpwd" type="password"><button class="gold" onclick="financeLogin()">查看報表</button></section>',true);var rows=db.cfg.stores.map(s=>{var os=db.orders.filter(o=>o.store===s);return'<tr><td>'+s+'</td><td>'+os.length+'</td><td>'+money(os.reduce((a,o)=>a+orderTotal(o),0))+'</td></tr>'}).join('');shell('財務報表統計','<section class="stats-grid">'+stat('總營收',money(db.orders.reduce((a,o)=>a+orderTotal(o),0)))+stat('完成訂單',db.orders.filter(o=>o.status==='已完工').length)+stat('客戶數',db.customers.length)+stat('施工人員',db.cfg.workers.length)+'</section><section class="table-wrap"><table><thead><tr><th>門市</th><th>訂單數</th><th>營業額</th></tr></thead><tbody>'+rows+'</tbody></table></section><button onclick="exportOrders()">匯出訂單CSV</button>',true)}function financeLogin(){if(v('fpwd')===FINANCE){db.finance=true;save();reports()}else alert('密碼錯誤')}
function logs(){if(!db.authed)return adminLogin();shell('操作紀錄','<section class="card">'+db.logs.map(l=>'<p>'+l+'</p>').join('')+'</section>',true)}function todayOrders(){var d=new Date().toISOString().slice(0,10);return db.orders.filter(o=>o.date===d)}function monthRevenue(){return db.orders.reduce((a,o)=>a+orderTotal(o),0)}
function csv(name,head,rows){var text=head+'
'+rows.join('
');var a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['﻿'+text],{type:'text/csv'}));a.download=name;a.click()}function exportOrders(){csv('orders.csv','訂單編號,客戶稱呼,車型,車牌,電話,日期,時間,門市,方案,加購,總金額,狀態,施工人員,備註',db.orders.map(o=>[o.id,o.name,o.car,o.plate,o.phone,o.date,o.time,o.store,pkg(o.packageId).name,addonNames(o.addonIds),orderTotal(o),o.status,worker(o.workerId).name,o.note].join(',')))}function exportCustomers(){csv('customers.csv','客戶編號,稱呼,電話,車牌,車型,門市,首次預約,消費總額,備註',db.customers.map(c=>[c.id,c.name,c.phone,c.plate,c.car,c.store,c.firstDate,c.total,c.note].join(',')))}
function render(){var r={home,frontForm,pasteForm,evalForm,siteForm,orders,calendar,customers,price,adminLogin,adminHome,config,workers,priceAdmin,reports,logs};(r[db.view]||home)()}window.go=go;window.calcMoney=calcMoney;window.saveOrder=saveOrder;window.parsePaste=parsePaste;window.openOrder=openOrder;window.changeStatus=changeStatus;window.changeWorker=changeWorker;window.addCfg=addCfg;window.addWorker=addWorker;window.delWorker=delWorker;window.addPackage=addPackage;window.delPackage=delPackage;window.login=login;window.logout=logout;window.financeLogin=financeLogin;window.exportOrders=exportOrders;window.exportCustomers=exportCustomers;window.orders=orders;window.calendar=calendar;window.customers=customers;window.db=db;render();
})();
