(function(){
var KEY='car-beauty-workbench-v6';
var ADMIN='admin1234', FINANCE='boss1688', MANAGER='store1688';
var seed={view:'home',authed:false,finance:false,role:'staff',notice:true,receptionists:['小芳','阿凱','Mina'],workers:['施工A組','施工B組','鍍膜師傅','內裝清潔師'],vehicles:[{id:1,code:'CAR-01',model:'Tesla Model Y',status:'可用'},{id:2,code:'CAR-02',model:'休旅車施工位',status:'可用'},{id:3,code:'CAR-03',model:'轎車施工位',status:'維保'}],services:[{id:1,group:'基礎服務套餐',name:'9999內外超值',price:9999,text:'外觀清潔、內裝整理、基礎護理一次完成。',active:true},{id:2,group:'基礎服務套餐',name:'內裝深層拆洗',price:7800,text:'座椅、地毯、門板深層清潔，適合家庭車、寵物車與中古車。',active:true},{id:3,group:'單項服務',name:'玻璃油膜鍍膜',price:3200,text:'改善雨天視線，增加玻璃撥水效果。',active:true},{id:4,group:'額外加購項目',name:'寵物異味處理',price:1500,text:'針對寵物味、毛髮與局部污漬加強處理。',active:true},{id:5,group:'額外加購項目',name:'煙味處理',price:1800,text:'車內煙味、霉味、異味加強處理。',active:true}],customers:[{name:'王先生',phone:'0911222333',level:'VIP',note:'Tesla白內裝'},{name:'林小姐',phone:'0922333444',level:'一般',note:'寵物車除味'}],orders:[{id:'O20260706001',type:'現場預約',name:'王先生',phone:'0911222333',level:'VIP',date:'2026-07-07',time:'10:00',vehicleId:1,receptionist:'小芳',workers:['施工A組','鍍膜師傅'],serviceIds:[1,3],prepaid:2000,pay:'匯款',status:'已排車',note:'白內裝加強',photos:[]},{id:'O20260706002',type:'後台預約',name:'林小姐',phone:'0922333444',level:'一般',date:'2026-07-08',time:'14:00',vehicleId:2,receptionist:'阿凱',workers:['施工B組'],serviceIds:[2,4],prepaid:1000,pay:'現金',status:'待確認',note:'寵物味',photos:[]}],expenseCategories:['藥水耗材','耗材物料','設備維修','房租人工','雜項開支'],expenses:[{id:'E1',date:'2026-07-06',category:'藥水耗材',amount:1800,pay:'現金',note:'清潔藥水補貨'}],logs:['系統建立測試資料'],outbox:[]};
var db=load();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||clone(seed)}catch(e){return clone(seed)}}
function clone(x){return JSON.parse(JSON.stringify(x))}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function q(id){return document.getElementById(id)}
function v(id){return (q(id)&&q(id).value||'').trim()}
function money(n){return '$'+Number(n||0).toLocaleString('zh-TW')}
function svc(ids){return ids.map(function(id){var s=db.services.find(function(x){return x.id==id});return s?s.name:''}).filter(Boolean).join('、')}
function total(o){return o.serviceIds.reduce(function(sum,id){var s=db.services.find(function(x){return x.id==id});return sum+(s?s.price:0)},0)}
function car(id){var c=db.vehicles.find(function(x){return x.id==id});return c?c.code+' '+c.model:'-'}
function log(t){db.logs.unshift(new Date().toLocaleString('zh-TW')+' '+t);save()}
function go(name){db.view=name;save();render()}
function tab(name,text){return '<button class="'+(db.view===name?'active':'')+'" onclick="go(\''+name+'\')"><strong>'+text[0]+'</strong>'+text+'</button>'}
function shell(title,body,admin){q('app').innerHTML='<header class="topbar worktop"><div><h1>'+title+'</h1><small>'+(admin?'後台管理端':'前台工作台')+' · '+(navigator.onLine?'線上':'離線可用')+'</small></div><button class="ghost" onclick="go(\''+(admin?'home':'adminLogin')+'\')">'+(admin?'回前台':'後台')+'</button></header>'+(admin&&db.authed?adminMenu():'')+'<main class="page">'+body+'</main><nav class="bottom-nav">'+tab('messages','通知')+tab('quick','快捷')+tab('home','工作台')+tab('customers','客戶')+tab('mine','我的')+'</nav>'}
function adminMenu(){return '<div class="admin-menu"><button onclick="go(\'adminHome\')">總覽</button><button onclick="go(\'people\')">人員</button><button onclick="go(\'vehicles\')">車輛</button><button onclick="go(\'services\')">服務價目</button><button onclick="go(\'allOrders\')">訂單</button><button onclick="go(\'reports\')">財務報表</button><button onclick="go(\'logs\')">紀錄</button><button class="secondary" onclick="logout()">登出</button></div>'}
function stat(a,b){return '<article class="card stat-card"><span>'+a+'</span><strong>'+b+'</strong></article>'}
function tool(view,text){return '<button class="tool" onclick="go(\''+view+'\')"><strong>'+text[0]+'</strong><span>'+text+'</span></button>'}
function home(){var today=new Date().toISOString().slice(0,10);var pending=db.orders.filter(function(o){return o.status==='待確認'}).length;shell('門店前台工作台','<section class="banner">汽車美容門店管理 APP · 預約、排車、施工相冊、支出都集中在這裡</section><section class="stats-grid">'+stat('待處理預約',pending)+stat('今日排車',db.orders.filter(function(o){return o.date===today}).length)+stat('待上傳施工圖',db.orders.filter(function(o){return !o.photos.length}).length)+stat('離線待同步',db.outbox.length)+'</section><section class="quick-pair"><button onclick="go(\'newOnsite\')">現場預約</button><button onclick="go(\'newBackstage\')">後台預約</button></section><h2>常用功能</h2><section class="tool-grid">'+tool('newOnsite','現場預約')+tool('newBackstage','後台預約')+tool('calendar','月行事曆')+tool('yearCalendar','年度行事曆')+tool('expense','支出填報')+tool('price','價目菜單')+tool('customers','客戶檔案')+tool('vehicleQuery','車輛查詢')+tool('albums','施工相冊')+'</section><h2>緊急待辦</h2><section class="todo-list">'+todo()+'</section>')}
function todo(){var list=db.orders.filter(function(o){return o.status==='待確認'||!o.photos.length}).slice(0,6);return list.length?list.map(function(o){return '<article class="todo"><span class="badge">!</span><div><b>'+(o.status==='待確認'?'逾期未確認':'待上傳施工圖')+'</b><p>'+o.name+' '+o.date+' '+o.time+' '+car(o.vehicleId)+'</p></div><button onclick="openOrder(\''+o.id+'\')">立即處理</button></article>'}).join(''):'<div class="empty">目前沒有待辦</div>'}
function field(label,id,need,value){return '<div class="field"><label>'+label+'</label><input id="'+id+'" '+(need?'required':'')+' value="'+(value||'')+'"></div>'}
function select(label,id,items){return '<div class="field"><label>'+label+'</label><select id="'+id+'">'+items.map(function(x){return typeof x==='string'?'<option>'+x+'</option>':'<option value="'+x.value+'">'+x.label+'</option>'}).join('')+'</select></div>'}
function orderForm(type){shell(type,'<form class="grid two" onsubmit="submitOrder(event,\''+type+'\')"><section class="card"><h2>客戶資料</h2>'+field('姓名','name',true)+field('電話','phone',true)+select('客戶等級','level',['一般','VIP','高意圖'])+field('備註','note',false)+field('預約日期','date',true,new Date().toISOString().slice(0,10))+select('時段','time',['09:00','10:00','11:00','13:00','14:00','15:00','16:00'])+'</section><section class="card"><h2>排車與服務</h2>'+select('車輛 / 施工位','vehicleId',db.vehicles.filter(function(x){return x.status==='可用'}).map(function(x){return {value:x.id,label:x.code+' '+x.model}}))+select('接待人員','receptionist',db.receptionists)+'<div class="field"><label>施工人員</label>'+db.workers.map(function(w){return '<label class="choice"><input name="workers" type="checkbox" value="'+w+'"> '+w+'</label>'}).join('')+'</div><div class="field"><label>服務項目</label>'+db.services.filter(function(s){return s.active}).map(function(s){return '<label class="choice"><input name="services" type="checkbox" value="'+s.id+'" onchange="calc()"> '+s.name+' '+money(s.price)+'</label>'}).join('')+'</div>'+field('預收金額','prepaid',false,'0')+select('支付方式','pay',['現金','匯款','訂金','刷卡'])+'<h3>總價 <span class="price" id="sum">$0</span></h3><button class="gold">建立預約</button></section></form>')}
function checked(name){return Array.from(document.querySelectorAll('input[name="'+name+'"]:checked')).map(function(i){return i.value})}
function calc(){var sum=checked('services').reduce(function(a,id){var s=db.services.find(function(x){return x.id==id});return a+(s?s.price:0)},0);q('sum').textContent=money(sum)}
function submitOrder(e,type){e.preventDefault();var date=v('date'),time=v('time'),vehicleId=Number(v('vehicleId'));if(db.orders.some(function(o){return o.date===date&&o.time===time&&Number(o.vehicleId)===vehicleId&&o.status!=='取消'})){alert('同一車輛同一時段已有預約，請更換時間或車輛。');return}var o={id:'O'+Date.now(),type:type,name:v('name'),phone:v('phone'),level:v('level'),date:date,time:time,vehicleId:vehicleId,receptionist:v('receptionist'),workers:checked('workers'),serviceIds:checked('services').map(Number),prepaid:Number(v('prepaid')||0),pay:v('pay'),status:'待確認',note:v('note'),photos:[]};db.orders.unshift(o);if(!db.customers.some(function(c){return c.phone===o.phone}))db.customers.unshift({name:o.name,phone:o.phone,level:o.level,note:o.note});db.outbox.push({type:'order',id:o.id});log('建立預約 '+o.id);save();alert('預約已建立');go('allOrders')}
function allOrders(){var rows=db.orders.map(function(o){return '<tr onclick="openOrder(\''+o.id+'\')"><td>'+o.id+'<br><span class="tag '+(o.type==='現場預約'?'green':'orange')+'">'+o.type+'</span></td><td>'+o.name+'<br>'+o.phone+'</td><td>'+o.date+' '+o.time+'<br>'+car(o.vehicleId)+'</td><td>'+svc(o.serviceIds)+'<br>'+money(total(o))+'</td><td><span class="tag">'+o.status+'</span></td></tr>'}).join('');shell('預約訂單','<section class="table-wrap"><table><thead><tr><th>單號</th><th>客戶</th><th>排程</th><th>服務</th><th>狀態</th></tr></thead><tbody>'+rows+'</tbody></table></section>',db.authed)}
function openOrder(id){var o=db.orders.find(function(x){return x.id===id});shell('訂單詳情','<section class="card"><h2>'+o.name+' <span class="tag">'+o.status+'</span></h2><p>'+o.phone+'<br>'+o.date+' '+o.time+'<br>'+car(o.vehicleId)+'<br>'+svc(o.serviceIds)+'</p><p>接待：'+o.receptionist+'<br>施工：'+(o.workers.join('、')||'-')+'</p><p class="price">'+money(total(o))+'</p><div class="row">'+['待確認','已排車','施工中','已完工','取消'].map(function(s){return '<button onclick="setStatus(\''+id+'\',\''+s+'\')">'+s+'</button>'}).join('')+'</div></section><section class="card"><h3>施工相冊</h3><input id="photos" type="file" accept="image/*" multiple><button onclick="savePhotos(\''+id+'\')">上傳照片</button><p>'+(o.photos.length?o.photos.join('、'):'尚未上傳')+'</p></section>',db.authed)}
function setStatus(id,s){var o=db.orders.find(function(x){return x.id===id});o.status=s;log(id+' 改為 '+s);save();openOrder(id)}
function savePhotos(id){var o=db.orders.find(function(x){return x.id===id});o.photos=o.photos.concat(Array.from(q('photos').files).map(function(f){return f.name}));db.outbox.push({type:'photos',id:id});log('上傳施工照片 '+id);save();openOrder(id)}
function calendar(){var days=Array.from(new Set(db.orders.map(function(o){return o.date}))).sort();shell('月行事曆','<section class="grid cards">'+days.map(function(d){return '<article class="card"><h3>'+d+'</h3>'+db.orders.filter(function(o){return o.date===d}).map(function(o){return '<p><span class="tag '+(o.type==='現場預約'?'green':'orange')+'">'+o.time+'</span> '+o.name+' '+car(o.vehicleId)+' '+svc(o.serviceIds)+'</p>'}).join('')+'</article>'}).join('')+'</section>')}
function yearCalendar(){var html='<section class="grid cards">';for(var i=1;i<=12;i++){var m=String(i).padStart(2,'0'),n=db.orders.filter(function(o){return o.date.slice(5,7)===m}).length;html+='<article class="card"><h3>'+m+'月</h3><p>'+n+' 台預約</p><span class="tag '+(n>8?'red':n>3?'orange':'green')+'">'+(n>8?'滿檔':n>3?'高峰':'空閒')+'</span></article>'}shell('年度行事曆',html+'</section>')}
function price(){var groups=Array.from(new Set(db.services.map(function(s){return s.group})));shell('服務菜單與價目',groups.map(function(g){return '<h2>'+g+'</h2><section class="grid cards">'+db.services.filter(function(s){return s.group===g&&s.active}).map(function(s){return '<article class="card"><h3>'+s.name+'</h3><p>'+s.text+'</p><p class="price">'+money(s.price)+'</p></article>'}).join('')+'</section>'}).join(''))}
function vehicleQuery(){shell('車輛查詢','<section class="grid cards">'+db.vehicles.map(function(v){return '<article class="card"><h3>'+v.code+'</h3><p>'+v.model+'</p><span class="tag '+(v.status==='可用'?'green':'orange')+'">'+v.status+'</span></article>'}).join('')+'</section>')}
function customers(){shell('客戶檔案','<section class="table-wrap"><table><thead><tr><th>姓名</th><th>電話</th><th>等級</th><th>備註</th></tr></thead><tbody>'+db.customers.map(function(c){return '<tr><td>'+c.name+'</td><td>'+c.phone+'</td><td>'+c.level+'</td><td>'+(c.note||'')+'</td></tr>'}).join('')+'</tbody></table></section>')}
function albums(){shell('施工相冊','<section class="grid cards">'+db.orders.map(function(o){return '<article class="card"><h3>'+o.name+' '+o.date+'</h3><p>'+car(o.vehicleId)+'</p><p>'+(o.photos.length?o.photos.join('、'):'尚未上傳')+'</p></article>'}).join('')+'</section>',db.authed)}
function expense(){if(db.role==='staff')return shell('支出填報','<section class="card"><h2>店長權限</h2><p>普通店員不顯示支出權限，請切換店長或由管理者操作。</p><button onclick="db.role=\'manager\';save();go(\'expense\')">切換店長測試</button></section>');shell('支出填報','<section class="card login-card"><p>請輸入店長操作密碼</p><input id="mpwd" type="password"><button class="gold" onclick="managerExpense()">進入填報</button></section>')}
function managerExpense(){if(v('mpwd')!==MANAGER)return alert('密碼錯誤');shell('新增支出','<form class="card" onsubmit="submitExpense(event)">'+field('支出日期','edate',true,new Date().toISOString().slice(0,10))+select('支出分類','ecat',db.expenseCategories)+field('支出金額','eamount',true)+select('付款方式','epay',['現金','匯款','刷卡'])+field('備註','enote',false)+'<button class="gold">送出支出</button></form>')}
function submitExpense(e){e.preventDefault();db.expenses.unshift({id:'E'+Date.now(),date:v('edate'),category:v('ecat'),amount:Number(v('eamount')||0),pay:v('epay'),note:v('enote')});db.outbox.push({type:'expense'});log('新增支出');save();alert('支出已保存');go('home')}
function adminLogin(){shell('管理後台登入','<section class="card login-card"><p>請輸入管理密碼</p><input id="pwd" type="password"><button class="gold" onclick="login()">登入後台</button><p class="muted">測試密碼：admin1234</p></section>',true)}
function login(){if(v('pwd')===ADMIN){db.authed=true;db.role='admin';save();go('adminHome')}else alert('密碼錯誤')}
function logout(){db.authed=false;db.finance=false;db.role='staff';save();go('home')}
function adminHome(){if(!db.authed)return adminLogin();var r=db.orders.reduce(function(s,o){return s+total(o)},0),e=db.expenses.reduce(function(s,x){return s+Number(x.amount||0)},0);shell('後台管理總覽','<section class="stats-grid">'+stat('本月預約',db.orders.length)+stat('總營收',money(r))+stat('總支出',money(e))+stat('淨盈利',money(r-e))+stat('新增客戶',db.customers.length)+stat('車輛閒置天數','3')+'</section><section class="tool-grid">'+tool('people','人員配置')+tool('vehicles','車輛管理')+tool('services','服務價目')+tool('allOrders','預約總控')+tool('reports','財務報表')+tool('logs','操作紀錄')+'</section>',true)}
function people(){if(!db.authed)return adminLogin();shell('人員配置管理','<section class="grid two"><article class="card"><h3>接待人員</h3>'+db.receptionists.map(function(p){return '<p>'+p+'</p>'}).join('')+'<button onclick="addPerson(\'receptionists\')">新增接待</button></article><article class="card"><h3>施工人員 / 班組</h3>'+db.workers.map(function(p){return '<p>'+p+'</p>'}).join('')+'<button onclick="addPerson(\'workers\')">新增施工</button></article></section>',true)}
function addPerson(type){var name=prompt('請輸入名稱');if(name){db[type].push(name);log('新增人員 '+name);save();people()}}
function vehicles(){if(!db.authed)return adminLogin();shell('車輛檔案庫','<section class="grid cards">'+db.vehicles.map(function(v){return '<article class="card"><h3>'+v.code+'</h3><p>'+v.model+'</p><span class="tag">'+v.status+'</span></article>'}).join('')+'<button onclick="addVehicle()">新增車輛</button></section>',true)}
function addVehicle(){db.vehicles.push({id:Date.now(),code:prompt('車輛編號','CAR-04'),model:prompt('車款型號','新施工位'),status:'可用'});log('新增車輛');save();vehicles()}
function services(){if(!db.authed)return adminLogin();shell('服務菜單與價目配置','<button onclick="addService()">新增服務</button><section class="grid cards">'+db.services.map(function(s){return '<article class="card"><h3>'+s.name+'</h3><p>'+s.group+'</p><p>'+s.text+'</p><p class="price">'+money(s.price)+'</p></article>'}).join('')+'</section>',true)}
function addService(){db.services.push({id:Date.now(),group:'單項服務',name:prompt('服務名稱','新服務'),price:Number(prompt('售價','0')),text:prompt('介紹',''),active:true});log('新增服務');save();services()}
function reports(){if(!db.authed)return adminLogin();if(!db.finance)return shell('財務二次驗證','<section class="card login-card"><p>請輸入財務密碼</p><input id="fpwd" type="password"><button class="gold" onclick="financeLogin()">查看報表</button><p class="muted">測試密碼：boss1688</p></section>',true);var r=db.orders.reduce(function(s,o){return s+total(o)},0),e=db.expenses.reduce(function(s,x){return s+Number(x.amount||0)},0);shell('財務報表','<section class="stats-grid">'+stat('現金收入',money(sumPay('現金')))+stat('匯款收入',money(sumPay('匯款')))+stat('訂金收入',money(sumPay('訂金')))+stat('刷卡收入',money(sumPay('刷卡')))+stat('總支出',money(e))+stat('淨利潤',money(r-e))+'</section><section class="table-wrap"><table><thead><tr><th>日期</th><th>分類</th><th>金額</th><th>備註</th></tr></thead><tbody>'+db.expenses.map(function(x){return '<tr><td>'+x.date+'</td><td>'+x.category+'</td><td>'+money(x.amount)+'</td><td>'+x.note+'</td></tr>'}).join('')+'</tbody></table></section><button onclick="exportCsv()">匯出CSV</button>',true)}
function financeLogin(){if(v('fpwd')===FINANCE){db.finance=true;save();reports()}else alert('密碼錯誤')}
function sumPay(pay){return db.orders.filter(function(o){return o.pay===pay}).reduce(function(s,o){return s+total(o)},0)}
function logs(){if(!db.authed)return adminLogin();shell('操作紀錄','<section class="card">'+db.logs.map(function(l){return '<p>'+l+'</p>'}).join('')+'</section>',true)}
function exportCsv(){var csv='單號,客戶,日期,金額\n'+db.orders.map(function(o){return o.id+','+o.name+','+o.date+','+total(o)}).join('\n');var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='report.csv';a.click()}
function messages(){shell('消息通知','<section class="card"><h2>APP 推送提醒</h2><p>'+(db.notice?'已開啟':'已關閉')+'。PWA 版先以站內提醒與紅點呈現。</p><button onclick="db.notice=!db.notice;save();messages()">切換提醒</button></section><section class="todo-list">'+todo()+'</section>')}
function quick(){shell('自訂快捷入口','<section class="tool-grid">'+tool('newOnsite','現場預約')+tool('newBackstage','後台預約')+tool('allOrders','預約列表')+tool('price','價目菜單')+tool('calendar','行事曆')+tool('adminLogin','後台')+'</section>')}
function mine(){shell('我的','<section class="card"><h2>目前角色：'+db.role+'</h2><p>離線待同步：'+db.outbox.length+' 筆</p><button onclick="syncNow()">手動同步</button><button onclick="db.role=db.role===\'staff\'?\'manager\':\'staff\';save();mine()">切換店員/店長</button><button class="secondary" onclick="go(\'adminLogin\')">管理後台</button></section>')}
function syncNow(){db.outbox=[];log('模擬同步完成');save();alert('已模擬同步完成');render()}
function render(){var r={home:home,newOnsite:function(){orderForm('現場預約')},newBackstage:function(){orderForm('後台預約')},calendar:calendar,yearCalendar:yearCalendar,expense:expense,price:price,vehicleQuery:vehicleQuery,customers:customers,albums:albums,allOrders:allOrders,adminLogin:adminLogin,adminHome:adminHome,people:people,vehicles:vehicles,services:services,reports:reports,logs:logs,messages:messages,quick:quick,mine:mine};(r[db.view]||home)()}
window.go=go;window.calc=calc;window.submitOrder=submitOrder;window.openOrder=openOrder;window.setStatus=setStatus;window.savePhotos=savePhotos;window.managerExpense=managerExpense;window.submitExpense=submitExpense;window.login=login;window.logout=logout;window.addPerson=addPerson;window.addVehicle=addVehicle;window.addService=addService;window.financeLogin=financeLogin;window.exportCsv=exportCsv;window.syncNow=syncNow;window.db=db;window.addEventListener('online',function(){if(db.outbox.length)syncNow()});render();
})();
