"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { Bar,BarChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import RequireAuth from "@/components/RequireAuth";
import { supabase } from "@/lib/supabase";
type Payment={amount:number;paid_at:string}; type Quote={id:string;status:string}; type Appointment={id:string;status:string};
export default function BiPage(){const [payments,setPayments]=useState<Payment[]>([]),[quotes,setQuotes]=useState<Quote[]>([]),[appointments,setAppointments]=useState<Appointment[]>([]);
 useEffect(()=>{Promise.all([supabase.from('payment').select('amount,paid_at,shop_id').order('paid_at',{ascending:false}).limit(5000),supabase.from('quotations').select('id,status,shop_id').limit(5000),supabase.from('appointments').select('id,status,shop_id').limit(5000)]).then(([p,q,a])=>{setPayments((p.data||[]) as Payment[]);setQuotes((q.data||[]) as Quote[]);setAppointments((a.data||[]) as Appointment[])})},[]);
 const revenue=payments.reduce((n,x)=>n+Number(x.amount||0),0),conversion=quotes.length?quotes.filter(x=>['confirmed','converted','completed'].includes(x.status)).length/quotes.length*100:0,arrival=appointments.length?appointments.filter(x=>!['cancelled','no_show'].includes(x.status)).length/appointments.length*100:0;
 const months=useMemo(()=>{const m=new Map<string,number>();payments.forEach(x=>{const k=String(x.paid_at).slice(0,7);m.set(k,(m.get(k)||0)+Number(x.amount||0))});return Array.from(m.entries()).sort().slice(-12).map(([month,amount])=>({month,amount}))},[payments]); const avg=payments.length?revenue/payments.length:0;
 return <RequireAuth><section className="space-y-5"><div className="card"><p className="text-sm font-black text-carcare-yellow">Management BI</p><h1 className="text-2xl font-black">老闆經營儀表板</h1><p className="text-sm text-neutral-500">數字依登入者可讀分店範圍計算；點卡片可下鑽至篩選清單。</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[`$${revenue.toLocaleString()}`,'累計營收','/finance/transactions'],[`$${Math.round(avg).toLocaleString()}`,'平均客單價','/finance/payments'],[`${conversion.toFixed(1)}%`,'報價成交率','/operations/quotations?status=confirmed'],[`${arrival.toFixed(1)}%`,'預約達成率','/operations/calendar?status=completed']].map(([v,l,h])=><Link key={l} href={h} className="card min-h-32 hover:border-carcare-yellow"><p className="text-sm font-bold text-neutral-500">{l}</p><p className="mt-3 text-3xl font-black">{v}</p><span className="mt-2 block text-xs text-neutral-500">查看明細 →</span></Link>)}</div><div className="card"><h2 className="text-lg font-black">月營收趨勢</h2><div className="mt-4 h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={months}><XAxis dataKey="month"/><YAxis/><Tooltip/><Bar dataKey="amount" fill="#ffc107" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="card"><h2 className="text-lg font-black">進階指標狀態</h2><p className="mt-2 text-sm text-neutral-600">毛利、客戶來源、回訪率、服務營收占比與員工績效，需待對應成本／來源欄位完成 tenant_id 回填後顯示，避免以不完整資料誤導管理決策。</p></div></section></RequireAuth>}

