"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import RequireAuth from "@/components/RequireAuth";
import { supabase } from "@/lib/supabase";

type Setting={id:string;category:string;setting_key:string;label:string;description?:string;value:unknown;shop_id?:string|null};
type Audit={id:number;action:string;table_name:string;record_id?:string;actor_role?:string;changed_fields?:string[];created_at:string;old_data?:unknown;new_data?:unknown};
type Backup={id:string;backup_type:string;status:string;retention_days:number;created_at:string;completed_at?:string;error_message?:string};
type Data={settings:Setting[];audits:Audit[];backups:Backup[];restores:unknown[];shops:{id:string;name:string;active:boolean}[]};
const categories=["公司基礎資料","分店營運","預約與工位","薪資獎金","PDF輸出","全域參數"];
const actionName:Record<string,string>={INSERT:"建立",UPDATE:"修改",DELETE:"刪除"};

async function authFetch(input:string,init?:RequestInit){const {data}=await supabase.auth.getSession();return fetch(input,{...init,headers:{"content-type":"application/json",Authorization:`Bearer ${data.session?.access_token||""}`,...init?.headers}})}

export default function EnterpriseSettingsPage(){
 const [tab,setTab]=useState<"settings"|"audit"|"backup">("settings"); const [data,setData]=useState<Data>({settings:[],audits:[],backups:[],restores:[],shops:[]});
 const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [query,setQuery]=useState(""); const [restoreTarget,setRestoreTarget]=useState(""); const [restoreText,setRestoreText]=useState("");
 const [form,setForm]=useState({category:categories[0],setting_key:"",label:"",value:"",description:"",shop_id:""});
 async function load(){setLoading(true);const r=await authFetch("/api/admin/enterprise",{cache:"no-store"});const j=await r.json();if(r.ok)setData(j);else setMessage(j.message||"讀取失敗");setLoading(false)}
 useEffect(()=>{load()},[]);
 async function save(){if(!form.setting_key||!form.label){setMessage("請填寫參數代碼與顯示名稱。");return}setLoading(true);let value:unknown=form.value;try{value=JSON.parse(form.value)}catch{}const r=await authFetch("/api/admin/enterprise",{method:"POST",body:JSON.stringify({action:"save_setting",...form,value,shop_id:form.shop_id||null})});const j=await r.json();setMessage(r.ok?"設定已儲存並寫入審計紀錄。":j.message||"儲存失敗");if(r.ok){setForm({...form,setting_key:"",label:"",value:"",description:""});await load()}else setLoading(false)}
 async function backup(){setLoading(true);const r=await authFetch("/api/admin/backup",{method:"POST",body:JSON.stringify({action:"run",retention_days:30})});const j=await r.json();setMessage(r.ok?`完整備份已完成：${j.table_count} 個資料表、${j.photo_count} 張施工照片。`:j.message||"建立失敗");await load()}
 async function restore(){if(restoreText!=="確認還原")return;setLoading(true);const r=await authFetch("/api/admin/backup",{method:"POST",body:JSON.stringify({action:"restore",backup_job_id:restoreTarget,confirm_text:restoreText,reason:"管理中心手動還原"})});const j=await r.json();setMessage(r.ok?`還原完成：${j.restored_tables} 個資料表、${j.restored_photos||0} 張照片。`:j.message||"還原失敗");setRestoreTarget("");setRestoreText("");await load()}
 const audits=useMemo(()=>data.audits.filter(x=>`${x.table_name} ${x.record_id||""} ${x.actor_role||""}`.toLowerCase().includes(query.toLowerCase())),[data.audits,query]);
 return <RequireAuth><section className="space-y-5">
  <div className="card"><p className="text-sm font-black text-carcare-yellow">Enterprise Control Center</p><h1 className="text-2xl font-black">系統設定與治理中心</h1><p className="mt-1 text-sm text-neutral-500">集中管理公司、分店、營運參數、稽核軌跡與備份工作。僅總管理員／店長可進入。</p></div>
  <div className="flex flex-wrap gap-2" role="tablist">{([['settings','系統參數'],['audit','Audit Log'],['backup','備份與還原']] as const).map(([k,v])=><button key={k} className={tab===k?"primary-btn":"secondary-btn"} onClick={()=>setTab(k)}>{v}</button>)}</div>
  {message&&<div className="rounded-xl border border-carcare-yellow/50 bg-carcare-yellow/10 p-3 text-sm font-bold">{message}</div>}
  {tab==='settings'&&<div className="grid gap-5 xl:grid-cols-[1fr_.8fr]">
   <div className="card"><h2 className="text-lg font-black">目前參數</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{data.settings.length?data.settings.map(s=><button key={s.id} className="min-h-24 rounded-xl border border-neutral-200 p-4 text-left hover:border-carcare-yellow" onClick={()=>setForm({category:s.category,setting_key:s.setting_key,label:s.label,value:typeof s.value==='string'?s.value:JSON.stringify(s.value,null,2),description:s.description||'',shop_id:s.shop_id||''})}><span className="text-xs text-neutral-500">{s.category}</span><strong className="mt-1 block">{s.label}</strong><span className="mt-1 block truncate text-sm text-neutral-600">{typeof s.value==='string'?s.value:JSON.stringify(s.value)}</span></button>):<p className="text-sm text-neutral-500">尚無自訂參數，可由右側建立。</p>}</div></div>
   <div className="card space-y-3"><h2 className="text-lg font-black">新增／編輯參數</h2><label className="block font-bold">分類<select className="form-input mt-1" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="block font-bold">分店<select className="form-input mt-1" value={form.shop_id} onChange={e=>setForm({...form,shop_id:e.target.value})}><option value="">全公司</option>{data.shops.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="block font-bold">参数代碼 *<input className="form-input mt-1" value={form.setting_key} onChange={e=>setForm({...form,setting_key:e.target.value.replace(/[^a-zA-Z0-9_.-]/g,'')})}/></label><label className="block font-bold">顯示名稱 *<input className="form-input mt-1" value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/></label><label className="block font-bold">設定值<input className="form-input mt-1" value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/><span className="mt-1 block text-xs text-neutral-500">可輸入文字、數字或 JSON。</span></label><label className="block font-bold">說明<textarea className="form-input mt-1 min-h-24" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="primary-btn w-full" disabled={loading} onClick={save}>{loading?'處理中…':'儲存設定'}</button><div className="grid grid-cols-2 gap-2"><Link className="secondary-btn text-center" href="/permissions">角色權限</Link><Link className="secondary-btn text-center" href="/operations/services">服務價格</Link></div></div>
  </div>}
  {tab==='audit'&&<div className="card"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-lg font-black">不可變更的操作紀錄</h2><p className="text-sm text-neutral-500">由資料庫 trigger 寫入，前端隱藏按鈕無法繞過。</p></div><div className="flex gap-2"><input className="form-input" placeholder="搜尋資料表、單號、角色" value={query} onChange={e=>setQuery(e.target.value)}/><button className="secondary-btn" onClick={()=>{const csv=['時間,動作,資料表,資料編號,角色,異動欄位',...audits.map(x=>[x.created_at,actionName[x.action]||x.action,x.table_name,x.record_id||'',x.actor_role||'',(x.changed_fields||[]).join('|')].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='audit-log.csv';a.click()}}>匯出 CSV</button></div></div><div className="mt-4 space-y-2">{audits.map(x=><details key={x.id} className="rounded-xl border border-neutral-200 p-3"><summary className="cursor-pointer list-none"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-neutral-900 px-2 py-1 text-xs font-black text-white">{actionName[x.action]||x.action}</span><strong>{x.table_name}</strong><span className="text-sm text-neutral-500">{x.record_id||'—'} · {new Date(x.created_at).toLocaleString('zh-TW')}</span></div></summary><pre className="mt-3 max-h-80 overflow-auto rounded-lg bg-neutral-950 p-3 text-xs text-neutral-100">{JSON.stringify({changed:x.changed_fields,before:x.old_data,after:x.new_data},null,2)}</pre></details>)}</div></div>}
  {tab==='backup'&&<div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="card space-y-3"><h2 className="text-lg font-black">備份政策</h2><p className="text-sm text-neutral-600">每日自動備份 Supabase Database 與 car-images Storage 實體照片，保留天數可在系統參數調整。</p><div className="rounded-xl border border-neutral-200 p-4"><strong>自動排程</strong><p className="text-sm text-neutral-500">每日執行、預設保留 30 天；還原必須輸入確認文字。</p></div><button className="primary-btn w-full" disabled={loading} onClick={backup}>立即建立完整備份</button></div><div className="card"><h2 className="text-lg font-black">最近備份</h2><div className="mt-4 space-y-3">{data.backups.length?data.backups.map(x=><div key={x.id} className="rounded-xl border border-neutral-200 p-4"><div className="flex items-center justify-between"><strong>{x.backup_type.toUpperCase()}</strong><span className={x.status==='failed'?'text-red-600':'text-neutral-700'}>{x.status}</span></div><p className="mt-1 text-sm text-neutral-500">{new Date(x.created_at).toLocaleString('zh-TW')} · 保留 {x.retention_days} 天</p>{x.status==='completed'&&<button className="secondary-btn mt-3" onClick={()=>setRestoreTarget(x.id)}>由此備份還原</button>}{x.error_message&&<p className="mt-2 text-sm text-red-600">{x.error_message}</p>}</div>):<p className="text-sm text-neutral-500">尚無備份工作。</p>}</div></div></div>}
  {restoreTarget&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4" role="dialog" aria-modal="true"><div className="card w-full max-w-md"><h2 className="text-xl font-black">確認還原完整資料</h2><p className="mt-2 text-sm text-neutral-600">此操作會以備份內容覆寫相同 ID 的資料與施工照片。請輸入「確認還原」。</p><input autoFocus className="form-input mt-4" value={restoreText} onChange={e=>setRestoreText(e.target.value)}/><div className="mt-4 flex gap-2"><button className="secondary-btn flex-1" onClick={()=>{setRestoreTarget('');setRestoreText('')}}>取消</button><button className="primary-btn flex-1" disabled={restoreText!=="確認還原"||loading} onClick={restore}>執行還原</button></div></div></div>}
 </section></RequireAuth>
}
